import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shared Recipe — Pantry to Plate",
  description: "A recipe generated by Pantry to Plate AI Chef from fridge ingredients. Powered by Groq & Llama 4 Vision.",
  openGraph: {
    title: "Shared Recipe — Pantry to Plate",
    description: "A recipe generated by Pantry to Plate AI Chef from fridge ingredients.",
    type: "article",
    images: [{ url: "/api/og?title=Shared+Recipe&tag=special", width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Shared Recipe — Pantry to Plate",
    description: "A recipe generated by Pantry to Plate AI Chef from fridge ingredients.",
    images: ["/api/og?title=Shared+Recipe&tag=special"],
  },
};

export default function ShareLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
