import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Recipe — Pantry to Plate",
  description: "A recipe generated by Pantry to Plate AI Chef from fridge ingredients.",
  openGraph: {
    title: "Recipe — Pantry to Plate",
    description: "A recipe generated by Pantry to Plate AI Chef from fridge ingredients.",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Recipe — Pantry to Plate",
    description: "A recipe generated by Pantry to Plate AI Chef from fridge ingredients.",
  },
};

export default function RecipeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
